import React, { useState } from 'react'
import { useRouter } from "next/router";
import Head from 'next/head'
import Link from 'next/link'
import axios from 'axios'
import styles from '../../styles/Home.module.scss'

export default function Login() {
    const [username, setUsername] = useState('')
    const [password, setPassword] = useState('')

    const router = useRouter();

    const handleLogin = () => {

        axios.post('https://messager-be.onrender.com/login', {
            username, password
        })
            .then(function (response) {
                alert(response.data.message)
                localStorage.setItem('token_Message_App', response.data.token)
                setUsername('')
                setPassword('')
                router.push("/");

            })
            .catch(function (error) {
                alert(error.response.data)

            });
    }
    return (
        <div className={styles.login}>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon1.ico" />
            </Head>
            <h1>LOGIN</h1>
            <div>
                <p>Username</p>
                <i className="fa-solid fa-user"></i>
                <input
                    placeholder='Enter username'
                    value={username}
                    onChange={e => setUsername(e.target.value)}
                />
            </div>
            <br></br>
            <div>
                <p>Password</p>
                <i className="fa-solid fa-lock"></i>
                <input
                    type={'password'}
                    placeholder='Enter password'
                    value={password}
                    onChange={e => setPassword(e.target.value)}
                />
            </div>
            <div>
                {username == '' || password == '' ? (<button style={{ backgroundColor: 'gray', }}>LOGIN</button>) : (
                    <button onClick={handleLogin}>LOGIN</button>
                )}

            </div>
            <br></br>
            <span>Do not have an account ? <Link href="/signup"><strong>Signup</strong></Link></span>

        </div>
    )
}
