import React, { useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import axios from 'axios'
import styles from '../../styles/Home.module.scss'


export default function Login() {
    const [username, setUsername] = useState('')
    const [password, setPassword] = useState('')
    const [confirm, setConfirm] = useState('')

    const handleSignup = () => {

        const checkUsername = /^[a-z0-9_\.]+$/.exec(username);
        const checkPassword = /^[a-z0-9_\.]+$/.exec(password);

        if (checkUsername == null || checkPassword == null) {
            alert('Username or Password error !!')
        }
        else {
            axios.post('https://messager-be.onrender.com/signup', {
                username, password
            })
                .then(function (response) {
                    console.log(response);
                    alert(response.data)
                    setUsername('')
                    setPassword('')
                    setConfirm('')
                })
                .catch(function (error) {
                    console.log(error);
                    alert(error.response.data)
                });
        }




    }
    return (
        <div className={styles.login}>
            <Head>
                <title>Signup</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon1.ico" />
            </Head>
            <h1>SIGNUP</h1>
            <div>
                <p>Username</p>
                <i className="fa-solid fa-user"></i>
                <input
                    placeholder='Enter username'
                    value={username}
                    onChange={e => setUsername(e.target.value)}
                />
            </div>
            <br></br>
            <div>
                <p>Password</p>
                <i className="fa-solid fa-lock"></i>
                <input
                    type={'password'}
                    placeholder='Enter password'
                    value={password}
                    onChange={e => setPassword(e.target.value)}
                />
            </div>
            <br></br>
            <div>
                <p>Confirm Password</p>
                {password == confirm && password != '' && confirm != '' ? (
                    <i style={{ color: 'green' }} className="fa-solid fa-circle-check"></i>
                ) : (
                    <i style={{ color: 'gray' }} className="fa-solid fa-circle-check"></i>
                )}

                <input
                    type={'password'}
                    placeholder='Enter password'
                    value={confirm}
                    onChange={e => setConfirm(e.target.value)}
                />
            </div>
            <div>
                {username == '' || password == '' || password != confirm ? (<button style={{ backgroundColor: 'gray', }}>SIGNUP</button>) : (
                    <button onClick={handleSignup}>SIGNUP</button>
                )}
            </div>
            <br></br>
            <span>Do you already have an account ? <Link href="/login"><strong>Login</strong></Link></span>
        </div>
    )
}
